---
- name: setup jenkins node
hosts: tag_Name_Jenkins_node
vars:
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/jenkins_aws.pem"
tasks:
    - name: install git
      apt:
        name: git
        update_cache: yes
        state: latest

    - name: install maven
      apt:
        name: maven
        state: latest
