---
- name: setup jenkins node
  hosts: tag_Name_Jenkins_node
  tasks:
    - name: install git
      apt:
        name: git
        update_cache: yes
        state: latest

    - name: install maven
      apt:
        name: maven
        state: latest
